### ISSUE TITLE
feat Functioning Website

### ISSUE THREAD

**Issue by Carlomos7** [AudioNook/IT490-002#55]
### Description:
Create a wireframe and design for the website, set up the website infrastructure, develop the website frontend and backend, integrate them to create a fully functioning website, and test its functionality and user experience.

### Goal:
To create the foundation for a functioning website with an intuitive user experience.

### Tasks:
- [ ] #87 
- [x] #63
- [x] Set up the website infrastructure (web server, hosting, etc.)
- [ ] #73
- [ ] #93
- [ ] Integrate frontend and backend to create a fully functioning website
- [ ] Test the website functionality and user experience
