### ISSUE TITLE
feat Third Party Source

### ISSUE THREAD

**Issue by Carlomos7** [AudioNook/IT490-002#56]
### Description:
Research the Discogs API and how to access it, set up data collection scripts to automatically pull data from the Discogs API, configure data collection scripts to run at appropriate intervals, and store the collected data in the database.

### Goal:
To automatically collect data from the Discogs API and store it in the project database.

### Tasks:
- [x] #103
- [ ] Set up data collection scripts to automatically pull data from the Discogs API
- [ ] Configure data collection scripts to run at appropriate intervals
- [ ] Store the collected data in the database
