### ISSUE TITLE
feat Logging System

### ISSUE THREAD

**Issue by Carlomos7** [AudioNook/IT490-002#57]
### Description:
Research distributed event logging systems and implement them using RabbitMQ to set up event logging infrastructure, develop event logging system using the chosen technology, integrate it with other parts of the project, and test the event logging system to ensure it is functioning correctly.

### Goal:
To implement a distributed event logging system using RabbitMQ.

### Tasks:
- [x] Research how to use RabbitMQ to log events
- [x] Set up the logging infrastructure
- [ ] #76
- [x] Test the event logging system to ensure it's functioning correctly
