### ISSUE TITLE
feat Product Filtering and Sorting

### ISSUE THREAD

**Issue by Carlomos7** [AudioNook/IT490-002#69]
### Description:
Users can filter and sort products
### Goal(s):
- Enable users to find specific products
### Tasks:
- [ ] Research common filtering and sorting options for music shops
- [ ] Develop filtering by genre, decade, physical format, and name
- [ ] Implement filter additive feature
- [ ] Sort products by price, reviews, and latest
