### ISSUE TITLE
feat Digital Collection

### ISSUE THREAD

**Issue by Carlomos7** [AudioNook/IT490-002#70]
### Description:
Users can create a digital collection of their physical collection
### Goal(s):
- Enable users to manage their music collection digitally
### Tasks:
- [ ] Create a collection database table
- [ ] Implement collection updates on user purchases
- [ ] Develop user's public collection visibility selection feature
