### ISSUE TITLE
feat Reviews

### ISSUE THREAD

**Issue by Carlomos7** [AudioNook/IT490-002#71]
### Description:
Users can review products and sellers
### Goal(s):
- Enable users to share their opinions and experiences with others
### Tasks:
- [ ] Develop product review functionality and page
- [ ] Implement product review showing product details
- [ ] Create seller review functionality and page
- [ ] Display the seller's average rating on the seller page
- [ ] Develop reviews page
